prometheus:
  prometheusSpec:
    externalLabels:
      cluster: d-prometheus-remotewrite

    ## https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write    
    remoteWrite:
      - url: 'http://localhost:8081/api/v1/write'
    containers:
      - name: prom-remotewrite
        image: mcr.microsoft.com/azuremonitor/prometheus/promdev/prom-remotewrite:prom-remotewrite-20221102.1
        imagePullPolicy: Always
        ports:
          - name: rw-port
            containerPort: 8081
        livenessProbe:
          httpGet:
            path: /health
            port: rw-port
            # initialDelaySeconds: 10
            # timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: rw-port
            # initialDelaySeconds: 10
            # timeoutSeconds: 10
        env:
          - name: INGESTION_URL
            value: https://xbwbocvhlocp-yjk4.westeurope-1.metrics.ingest.monitor.azure.com/dataCollectionRules/dcr-2f72a4ca18854a9a82efd75fe9ac663d/streams/Microsoft-PrometheusMetrics/api/v1/write?api-version=2021-11-01-preview    # Get this value from your Azure Metrics workspace
          - name: LISTENING_PORT
            value: '8081'
          - name: IDENTITY_TYPE
            value: userAssigned
          - name: AZURE_CLIENT_ID
            value: 03492ae1-5dc3-4497-b760-01dd06eee7cb
          - name: CLUSTER
            value: d-prometheus-remotewrite
grafana:
  enabled: false